# Default values for dance.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

openshift-gitops:
  enabled: true
  channel: gitops-1.10
  argocd-namespace: developer-argocd
  workload-namespaces:
    - default
openshift-pipelines:
  enabled: true
  channel: pipelines-1.12
quay:
  enabled: true
  registry: quay.io
  username: admin
  password: admin

# Workaround: Helm will install all charts in a single
# namespace/name, forcing the chart to use non-standard
# namespaces/names.
stackrox-secured-cluster-services:
  allowNonstandardNamespace: true
  allowNonstandardReleaseName: true
