# Default values for rhtap-installer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

openshift-gitops:
  enabled: true
  channel: gitops-1.11
  argocd-namespace: rhtap-argocd
  workload-namespaces:
    - default
openshift-pipelines:
  enabled: true
  channel: pipelines-1.13

# Private values
# You may want to override those variables in another file (e.g. values-private.yaml)
acs:
  central-endpoint: ${ACS__CENTRAL_ENDPOINT}
  api-token: ${ACS__API_TOKEN}
developer-hub:
  app-config:
    auth:
      environment: development
      providers:
        github:
          development:
            clientId: ${GITHUB__APP__CLIENT_ID}
            clientSecret: ${GITHUB__APP__CLIENT_SECRET}
    integrations:
      github:
        - host: github.com
          apps:
            - appId: ${GITHUB__APP__APP_ID}
              clientId: ${GITHUB__APP__CLIENT_ID}
              clientSecret: ${GITHUB__APP__CLIENT_SECRET}
              webhookUrl: ${GITHUB__APP__WEBHOOK_URL}
              webhookSecret: ${GITHUB__APP__WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB__APP__PRIVATE_KEY}
    catalog:
      locations:
        - type: url
          target: ${DEVELOPER_HUB__CATALOG__URL}
      rules:
        - allow:
          - Component
          - System
          - Group
          - Resource
          - Location
          - Template
          - API
pipelines:
  pipelines-as-code:
    github:
      application-id: ${GITHUB__APP__APP_ID}
      private-key: |
        ${GITHUB__APP__PRIVATE_KEY}
      webhook-secret: ${GITHUB__APP__WEBHOOK_SECRET}