{{ if eq (len (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "centrals.platform.stackrox.io")) 0 }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhacs-operator
  namespace: rhacs-operator
spec:
  channel: {{ index .Values "acs" "channel" }}
  installPlanApproval: Automatic
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhacs-operator.v4.3.0
{{ end }}