{{ if eq (len (lookup "v1" "Namespace" "" (index .Values "openshift-gitops" "argocd-namespace"))) 0 }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ index .Values "openshift-gitops" "argocd-namespace" }}
{{ end }}