{{ if eq (len (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "applications.argoproj.io")) 0 }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: {{ index .Values "openshift-gitops" "channel" }}
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: openshift-gitops-operator.v1.10.1
{{ end }}